import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import "bootstrap/dist/css/bootstrap.css";
import "./css/customcss.css"
import "./css/light.css"
import { registerLicense } from '@syncfusion/ej2-base';

registerLicense('Mgo+DSMBaFt+QHFqVkNrWU5Ff0BAXWFKblp8RGZTfllgBShNYlxTR3ZbQ1RjQH9Wd01iX35Y;Mgo+DSMBPh8sVXJ1S0d+X1RPc0BDVHxLflF1VWpTflt6dVJWESFaRnZdQV1nSHdTf0RmWHdcdHJT;ORg4AjUWIQA/Gnt2VFhhQlJBfVpdXGpWfFN0RnNQdV91flRBcC0sT3RfQF5jTX9adkxiXH5Wc3BXQA==;MTc3NjY3N0AzMjMxMmUzMTJlMzMzNVpiNXVGc2lkNUdZT3RiS202YXZ6c3pZK3dGV2gycmdzd3VHcytwZTUvM009;MTc3NjY3OEAzMjMxMmUzMTJlMzMzNWtlNW1Yb3RxUmpVeERaRzRNaXVZQmNic05obmc5a3Zxa21pQUE4QlJueUE9;NRAiBiAaIQQuGjN/V0d+XU9Hc1RHQmJAYVF2R2BJdlRxcV9HZ0wgOX1dQl9gSXpSf0VqWHpfeHNcQmA=;MTc3NjY4MEAzMjMxMmUzMTJlMzMzNW9wdDRNaGJRdDZEV2R1WkUweDk3cEVCT2U4bkNLV21Mck9iWWVGOFIxUVk9;MTc3NjY4MUAzMjMxMmUzMTJlMzMzNVg1RmpmNENHVWRFZmZQcmd2TjhZdGJWKzRwNUYzUWh4NWU3d1d4RGJ6NE09;Mgo+DSMBMAY9C3t2VFhhQlJBfVpdXGpWfFN0RnNQdV91flRBcC0sT3RfQF5jTX9adkxiXH5XcHJVRw==;MTc3NjY4M0AzMjMxMmUzMTJlMzMzNWJ2NUtYSzNTb3ZJbGJxVVEvWGhjMlRSRHp4V20xSUtMUVdFOE9tdXBKK2s9;MTc3NjY4NEAzMjMxMmUzMTJlMzMzNUJWemFzRlpyODlDakE1VnJkajlFOCt0TGZKUXJBVHF0KzMvTDBHaDJnM009;MTc3NjY4NUAzMjMxMmUzMTJlMzMzNW9wdDRNaGJRdDZEV2R1WkUweDk3cEVCT2U4bkNLV21Mck9iWWVGOFIxUVk9');

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

